apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: additional-config-app
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  project: default
  source:
    path: Additional-Configs
    repoURL:  'https://github.com/vjkancherla/ArgoCD-Helm'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
