apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki-promtail
    release: my-loki
  name: my-loki-promtail
  namespace: loki
spec:
  ports:
  - name: http-metrics
    port: 3101
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/name: promtail
  type: ClusterIP
