datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: My-Prometheus
      type: prometheus
      #The my-prometheus-kube-prometh-prometheus SVC's ClusterIP:port
      url: http://my-prometheus-kube-prometh-prometheus.prometheus.svc:9090
      access: proxy
      isDefault: true
    - name: My-Loki
      type: loki
      #The service/my-loki SVC's ClusterIP:port
      url: http://my-loki.loki.svc:3100
      access: proxy
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    kubernetes:
      gnetId: 10000
      revision: 1
      datasource: My-Prometheus

persistence:
  size: 100Mi

#Create a serviceMonitor K8s Object to allow Prometheus to discover our WP pods for scraping
#Creating ServiceMonitor K8s Object is more efficient than updating rules in Prometheus
serviceMonitor:
  enabled: true
  #We need to add a label to the ServiceMonitor K8s Object.
  #Go to 51:29 minutes in https://www.youtube.com/watch?v=6xmWr7p5TE0
  labels:
    release: my-prometheus
