apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-istiod
  labels:
    app: my-istiod
    #This label, which is applied to the servicemonitor is essential for allow Prometheus to discover this servicemonitor
    release: my-prometheus
  namespace: istio-system
spec:
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      app: istiod
  endpoints:
  - port: http-monitoring
    path: /metrics
