environment: "dev"

message: "!!This is a DEV test!!"

##Values for dependency chart Ingress-nginx
ingress-nginx:
  commonLabels:
    app: my-simple-app

  controller:
    ingressClassResource:
      name: dev-nginx
    service:
      type: ClusterIP
    
