environment: "prod"

message: "!!This is a Prod test!!"

##Values for dependency chart Ingress-nginx
ingress-nginx:
  commonLabels:
    app: my-simple-app

  controller:
    ingressClassResource:
      name: prod-nginx
    service:
      type: ClusterIP
