apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
  namespace: {{.Values.environment}}
data:
  simple-app-index.html: |
   <html>
   <h1>Welcome</h1>
   </br>
   <h1>The message is: {{.Values.message}} </h1>
   </html>
