apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace:  {{.Values.environment}}
spec:
  selector:
    app: simple-app
    version: v1
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
